### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Nidev-lab** [KameyhaFacundo/Pedidos-Frontend#11]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar un logo junto al nombre.

## Resultado actual

• No se visualiza el logo.

## Captura

![image](https://github.com/KameyhaFacundo/Pedidos-Frontend/assets/53904695/6503308c-5fc4-4660-8cb4-e6b4e480ec12)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by IsaiasPadros** [comment]
El logo fue agregado.
