### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by Nidev-lab** [KameyhaFacundo/Pedidos-Frontend#12]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar un scroll horizontal. 

## Resultado actual

• Se encuentra scroll horizontal.

## Captura

![image](https://github.com/KameyhaFacundo/Pedidos-Frontend/assets/53904695/d5b972ab-8a7f-4227-98ac-b23b93b9250e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by IsaiasPadros** [comment]
Problema resuelto mediante el ajuste de margenes utilizados.
