### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [KameyhaFacundo/Pedidos-Frontend#13]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Agregue uno pedidos al carrito.

## Resultado esperado

• Que al ingresar al carrito encontrar un boton para comprar los producto agregados.

## Resultado actual

• Al ingresar al carrito no hay un boton para realizar mi compra.

## Captura

![image](https://github.com/KameyhaFacundo/Pedidos-Frontend/assets/53904695/4fd6f2fa-e4ca-4a75-92cb-69a545490a54)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by IsaiasPadros** [comment]
Boton de compras agregado, con distintas funcionalidades. Al comprar se vacia el carrito y tambien en caso de que no haya ningun elemento a comprar el boton no aparecera en las opciones para el usuario.
